In [24]:

from keras.models import load_model
from keras.preprocessing import image
import numpy as np

In [25]:
model = load_model("Skin_Diseases_1.h5")

In [26]:
img = image.load_img(r"C:\Users\Sri_Harshitha\Desktop\skin-disease-identification-using-ML-master\Dataset\Dataset\train\Psoriasis\images - 2020-04-26T194017.723.jpg",target_size = (64,64))

In [27]:
import numpy as np
x = image.img_to_array(img)
x = np.expand_dims(x,axis =0)
       

In [28]:
x.shape

(1, 64, 64, 3)

In [29]:
pred = model.predict(x)

In [30]:
l=np.amax(pred)
l

1.0

In [31]:
f=pred.astype(int)
f

array([[0, 0, 1, 0, 0]])

In [32]:
a1=np.array(f)
print(a1)

[[0 0 1 0 0]]


In [33]:
from functools import reduce


single_list = reduce(lambda x,y: x+y, a1)
print(single_list)


[0 0 1 0 0]


In [34]:
val=np.where(single_list==1)
dou_list = reduce(lambda x,y: x+y, val)
print(dou_list)


[2]


In [35]:
stringed = ''.join(map(str,val))
stringed
v=stringed[1]
v1= int(v)
v1

2

In [36]:
index = ['Acne', 'Melanoma', 'Psoriasis', 'Rosacea', 'Vitiligo']

In [37]:
index[v1]

'Psoriasis'